#!/usr/bin/env bash
# =============================================================================
# dsh-hermes-collab-pipeline 一键安装脚本
#
# ⚠️ AI-GENERATED CODE: This script was generated by DeepSeek AI and has NOT
# been human-reviewed. Review before running on production systems.
#
# 设计目标：
#   - 人工可用：每步有 [OK]/[SKIP]/[FAIL] 输出，失败即停并给原因
#   - Agent 可用：--yes 全自动、--dry-run 预演、幂等可重跑、退出码可判断
#   - 幂等：重复运行不会重复修改（已应用的跳过）
#
# 用法：
#   ./install.sh                    # 交互式（每步确认）
#   ./install.sh --yes              # 全自动（agent 用这个）
#   ./install.sh --dry-run          # 只打印将要做什么，不执行
#   ./install.sh --workspace ~/DSH  # 指定 DSH 工作区（默认 ~/DSH）
#   ./install.sh --skip-systemd     # 跳过 systemd 服务安装
#
# 退出码：0=全部成功/跳过  1=有失败  2=前置条件不满足
# =============================================================================

set -u
# 不用 set -e：我们要自己控制每步的成败判断和输出

# ---------- 参数解析 ----------
YES=0
DRY_RUN=0
WORKSPACE="${DSH_WORKSPACE:-$HOME/DSH}"
SKIP_SYSTEMD=0
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

for arg in "$@"; do
  case "$arg" in
    --yes|-y)        YES=1 ;;
    --dry-run)       DRY_RUN=1 ;;
    --skip-systemd)  SKIP_SYSTEMD=1 ;;
    --workspace=*)   WORKSPACE="${arg#*=}" ;;
    --workspace)     echo "用法: --workspace=<路径>"; exit 2 ;;
    --help|-h)       grep '^#' "$0" | head -20; exit 0 ;;
    *)               echo "未知参数: $arg（--help 查看用法）"; exit 2 ;;
  esac
done

# ---------- 工具函数 ----------
PASS=0; FAIL=1; SKIP=2
log()  { printf '\033[32m[OK]\033[0m   %s\n' "$1"; }
warn() { printf '\033[33m[SKIP]\033[0m %s\n' "$1"; }
err()  { printf '\033[31m[FAIL]\033[0m %s\n' "$1"; }
info() { printf '\033[36m[INFO]\033[0m %s\n' "$1"; }

# 确认或 --yes 直通；--dry-run 不执行
confirm() {
  local desc="$1"
  if [ "$DRY_RUN" = "1" ]; then
    info "预演: $desc"
    return 0
  fi
  if [ "$YES" = "1" ]; then
    return 0
  fi
  read -r -p "执行: $desc ? [y/N] " ans
  [ "$ans" = "y" ] || [ "$ans" = "Y" ]
}

run() {
  if [ "$DRY_RUN" = "1" ]; then
    info "预演命令: $*"
    return 0
  fi
  "$@" 2>&1
}

# 探测命令是否存在
have() { command -v "$1" >/dev/null 2>&1; }

# ---------- 前置检查 ----------
info "仓库目录: $REPO_DIR"
info "DSH 工作区: $WORKSPACE"

PREREQ_OK=1
for cmd in hermes node npm; do
  if have "$cmd"; then
    log "找到 $cmd: $(command -v "$cmd")"
  else
    err "缺少 $cmd —— 请先安装（Hermes: 官方脚本；node/npm: Node 运行时）"
    PREREQ_OK=0
  fi
done

# pnpm 不是硬依赖：优先 pnpm，没有则 corepack 或 npm 兜底（都能装 file: 本地包）
if have pnpm; then
  PKG_MGR="pnpm"
  log "找到 pnpm: $(command -v pnpm)"
elif have corepack; then
  PKG_MGR="corepack pnpm"
  log "未找到 pnpm，用 corepack pnpm 兜底"
else
  PKG_MGR="npm"
  warn "未找到 pnpm/corepack，用 npm 兜底（file: 本地包同样可装）"
fi

# dsh CLI（npm 全局包，命令名可能是 dsh）
if have dsh; then
  log "找到 dsh: $(command -v dsh)"
else
  DSH_BIN="$(npm prefix -g 2>/dev/null)/bin/dsh"
  if [ -x "$DSH_BIN" ]; then
    log "找到 dsh（npm 全局）: $DSH_BIN"
  else
    err "缺少 dsh —— 请先安装: npm install -g @deepseek-ai/dsh"
    PREREQ_OK=0
  fi
fi

# DSH web profile（插件要装进这里）
WEB_PROFILE="$HOME/.dsh/profiles/web"
if [ -d "$WEB_PROFILE" ]; then
  log "找到 DSH web profile: $WEB_PROFILE"
else
  err "DSH web profile 不存在: $WEB_PROFILE"
  err "先运行一次: dsh web --port 3080（首次启动会自动初始化 profile），然后 Ctrl+C 停掉再跑本脚本"
  PREREQ_OK=0
fi

# 插件源码
PLUGIN_DIR="$REPO_DIR/dsh-side/plugins/dsh-kanban-watcher"
if [ -f "$PLUGIN_DIR/package.json" ]; then
  log "找到插件源码: $PLUGIN_DIR"
else
  err "找不到插件源码: $PLUGIN_DIR（确认在仓库根目录运行本脚本）"
  PREREQ_OK=0
fi

# Hermes 源码目录
HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
HERMES_AGENT_DIR="$HERMES_HOME/hermes-agent"
if [ -d "$HERMES_AGENT_DIR" ]; then
  log "找到 Hermes 源码: $HERMES_AGENT_DIR"
else
  err "找不到 Hermes 源码: $HERMES_AGENT_DIR（patch 需要应用到这里）"
  PREREQ_OK=0
fi

if [ "$PREREQ_OK" != "1" ]; then
  err "前置条件不满足，中止。"
  exit 2
fi

# ---------- 1. kanban board 初始化（幂等） ----------
if confirm "初始化 kanban board 'dsh'"; then
  if hermes kanban boards 2>/dev/null | grep -qw dsh; then
    warn "board dsh 已存在，跳过"
  else
    out=$(run hermes kanban boards create dsh 2>&1)
    if [ $? -eq 0 ]; then log "创建 board dsh"; else err "创建失败: $out"; exit 1; fi
  fi
fi

# ---------- 2. 安装 watcher 插件（幂等） ----------
if confirm "安装 watcher 插件到 DSH web profile"; then
  if grep -q '"dsh-kanban-watcher"' "$WEB_PROFILE/package.json" 2>/dev/null \
     || [ -d "$WEB_PROFILE/node_modules/dsh-kanban-watcher" ]; then
    warn "插件已安装，跳过"
  else
    out=$(run bash -c "cd '$WEB_PROFILE' && $PKG_MGR add file:'$PLUGIN_DIR'" 2>&1)
    if [ $? -eq 0 ]; then log "插件已安装（pnpm 输出含 'declares no dsh.bundle' 警告属预期）"; else err "安装失败: $out"; exit 1; fi
  fi
fi

# ---------- 3. cordis.patch.yml 挂载（幂等） ----------
PATCH_YML="$WEB_PROFILE/cordis.patch.yml"
if confirm "挂载 kanban-watcher 插件行到 cordis.patch.yml"; then
  if [ -f "$PATCH_YML" ] && grep -q 'kanban-watcher' "$PATCH_YML" 2>/dev/null; then
    warn "cordis.patch.yml 已含 kanban-watcher，跳过"
  else
    cat >> "$PATCH_YML" << EOF

- insert:
    - id: kanban-watcher
      name: 'dsh-kanban-watcher'
      config:
        board: 'dsh'
        assignee: 'dsh'
        triggerDir: '$HOME/.dsh/kanban-trigger'
        pollIntervalMs: 30000
        allowedOutputDirs:
          - '$WORKSPACE'
        modelMap:
          'deepseek-v4-flash': { provider: 'deepseek-official', model: 'deepseek-v4-flash' }
          '__fallback__':      { provider: 'deepseek-official', model: 'deepseek-v4-flash' }
EOF
    log "已挂载（请人工核对路径 $WORKSPACE 是否正确）"
  fi
fi

# ---------- 4. 应用 Hermes patch（幂等） ----------
PATCH_FILE="$REPO_DIR/hermes-side/hermes-external-event-steer.patch"
if confirm "应用 external_event_steer patch 到 Hermes 源码"; then
  if grep -q '_drain_done_notifications' "$HERMES_AGENT_DIR/cli.py" 2>/dev/null; then
    warn "patch 已应用，跳过"
  else
    out=$(run bash -c "cd '$HERMES_AGENT_DIR' && git apply --check '$PATCH_FILE'" 2>&1)
    if [ $? -ne 0 ]; then
      err "git apply --check 失败（版本差异？）："
      echo "$out"
      err "处理：见 INSTALL-安装指南.md 的「patch 冲突处理」节（git apply -3 或手动改）"
      exit 1
    fi
    out=$(run bash -c "cd '$HERMES_AGENT_DIR' && git apply '$PATCH_FILE'" 2>&1)
    if [ $? -eq 0 ]; then log "patch 已应用"; else err "应用失败: $out"; exit 1; fi
  fi
fi

# ---------- 5. 开启配置开关（幂等） ----------
if confirm "开启 features.external_event_steer"; then
  if hermes config get features.external_event_steer 2>/dev/null | grep -q true; then
    warn "开关已开启，跳过"
  else
    out=$(run hermes config set features.external_event_steer true 2>&1)
    if [ $? -eq 0 ]; then log "已开启 external_event_steer"; else err "设置失败: $out"; exit 1; fi
  fi
fi

# ---------- 6. 部署 dsh-send 技能（幂等） ----------
SKILL_SRC="$REPO_DIR/hermes-side/dsh-send-skill"
SKILL_DST="$HERMES_HOME/skills/devops/dsh-send"
if confirm "部署 /dsh-send 技能到 Hermes"; then
  if [ -f "$SKILL_DST/SKILL.md" ]; then
    warn "技能已存在，跳过（如需更新: cp -r '$SKILL_SRC/.' '$SKILL_DST/'）"
  else
    out=$(run bash -c "mkdir -p '$HERMES_HOME/skills/devops' && cp -r '$SKILL_SRC' '$SKILL_DST'" 2>&1)
    if [ $? -eq 0 ]; then log "技能已部署到 $SKILL_DST"; else err "部署失败: $out"; exit 1; fi
  fi
fi

# ---------- 7. systemd 服务（可选） ----------
if [ "$SKIP_SYSTEMD" = "0" ] && confirm "安装 dsh-web systemd 服务（模板）"; then
  SVC_DST="$HOME/.config/systemd/user/dsh-web.service"
  if [ -f "$SVC_DST" ]; then
    warn "服务文件已存在，跳过"
  else
    # 模板里 <DSH_BIN> 和 <NPM_PREFIX> 自动替换为探测值
    DSH_BIN_FULL="$(command -v dsh 2>/dev/null || echo "$(npm prefix -g)/bin/dsh")"
    NPM_PREFIX="$(npm prefix -g 2>/dev/null)"
    mkdir -p "$(dirname "$SVC_DST")"
    sed -e "s|<DSH_BIN>|$DSH_BIN_FULL|g" \
        -e "s|<NPM_PREFIX>|$NPM_PREFIX|g" \
        -e "s|/home/alice|$HOME|g" \
        "$REPO_DIR/hermes-side/dsh-web.service" > "$SVC_DST"
    log "服务文件已生成: $SVC_DST（运行 systemctl --user daemon-reload && enable --now 启用）"
  fi
fi

# ---------- 8. 验证 ----------
if confirm "运行验证"; then
  info "== 验证 =="
  hermes kanban boards 2>/dev/null | grep -q dsh && log "kanban board dsh ✓" || warn "board dsh 未找到"
  [ -d "$WEB_PROFILE/node_modules/dsh-kanban-watcher" ] && log "插件已装 ✓" || warn "插件未装"
  grep -q 'kanban-watcher' "$PATCH_YML" 2>/dev/null && log "插件已挂载 ✓" || warn "插件未挂载"
  grep -q '_drain_done_notifications' "$HERMES_AGENT_DIR/cli.py" 2>/dev/null && log "patch 已应用 ✓" || warn "patch 未应用"
  curl -s -o /dev/null --max-time 3 http://127.0.0.1:3080 && log "dsh web 运行中 ✓" || warn "dsh web 未运行（先启动: dsh web --port 3080）"
fi

info ""
info "安装流程完成。下一步："
info "  1. 启动 dsh web（若未运行）: dsh web --port 3080"
info "  2. 重启 Hermes CLI 会话（新代码+新技能生效）"
info "  3. 在 Hermes 里试: /dsh-send 测试一下，写一句话到 DSH 工作区"
exit 0
