// dsh-kanban-watcher — 监听 Hermes kanban 看板、把任务交给 DSH Agent 执行的 Cordis 插件。
//
// ⚠️ AI-GENERATED CODE: This file was generated by DeepSeek AI and has NOT been
// human-reviewed. Review security-critical paths (permission presets, output
// whitelist, file writes) before deployment.
//
// 定位：DSH ↔ Hermes 双 Agent 协作管道的「执行侧」。Hermes 通过 /dsh-send 技能把任务
// 写入看板（board: dsh）并写触发文件唤醒本插件；插件认领 ready 任务 → 用 DSH 的
// agents.create 开启带 GUI 会话的 agent 执行 → 把结果回写看板（comment + complete），
// 并写 done 文件通知 Hermes 侧（外部事件注入）。
//
// 对 Hermes kanban CLI 的关键事实（均经实测确认，勿按直觉假设）：
//   - `list --json` 返回纯数组（不是 {tasks:[...]}）；`show --json` 返回
//     {task, comments, events}，取 `.task` 才是任务本体
//   - `claim <id>` 没有 --assignee（assignee 在 create 时固定）；`reclaim <id> [--reason]`
//   - `comment <id> <text...>` 是位置参数；`complete <id> --result <text>`
//   - `block <id> <reason...> --kind <capability|dependency|needs_input|transient>`
//   - 模型字段名是 model_override / provider_override（resolveModel 读取）
//   - 终态是 done（不是 completed）；只认领 status === "ready" 的任务
//   - 会话必须 attach 到工作区（workspaceRegistry），否则 GUI 侧边栏看不到该会话
import { randomUUID } from "node:crypto";
import { execFileSync } from "node:child_process";
import {
  watch as fsWatch, readdirSync, rmSync, readFileSync,
  mkdirSync, openSync, closeSync, writeSync, writeFileSync
} from "node:fs";
import { homedir } from "node:os";
import { basename, dirname, join } from "node:path";
import z from "@deepseek-ai/schemastery";
import { installModelSelection } from "@deepseek-ai/dsh-agent";
import { createUserMessage } from "@deepseek-ai/dsh-llm";
import { SessionId } from "@deepseek-ai/dsh-session";

const name = "kanban-watcher";
const inject = ["agentDefaultModel", "agents", "sessions", "workspaceRegistry", "agentPresets", "permissionPresets"];

const Config = z.object({
  hermesBin: z.string().default("$HERMES_BIN"),
  board: z.string().default("dsh"),
  assignee: z.string().default("dsh"),
  triggerDir: z.string().default("$DSH_TRIGGER_DIR"),
  // done 文件目录：Hermes 侧外部事件注入默认监听 ~/.dsh/kanban-done/，可用 HERMES_DONE_WATCH_DIR 覆盖
  doneDir: z.string().default("$DSH_DONE_DIR"),
  pollIntervalMs: z.number().default(30000),
  taskTimeoutMs: z.number().default(600000),
  // watcher 会话专用权限预设：workspace-write + ask 会让白名单外路径（如 /mnt/c）被拒、
  // 无人应答的审批请求挂起死锁，故用 danger-full-access + never 的组合
  permissionPreset: z.string().default("hermes-trusted"),
  cwd: z.string().default("$DSH_WORKSPACE"),
  allowedOutputDirs: z.array(z.string()).default(["$DSH_WORKSPACE", "$DESKTOP"]),
  // schemastery 3.x 无 passthrough()（那是 zod API）；dict(any) 等价且更贴切
  modelMap: z.dict(z.any()).default({
    "deepseek-v4-flash": { provider: "deepseek-official", model: "deepseek-v4-flash" },
    "__fallback__": { provider: "deepseek-official", model: "deepseek-v4-flash" }
  })
});

let log = (...a) => console.log("[kanban-watcher]", ...a);

/** 超时包装：agent 审批无人应答时 whenIdle 可能永久挂起、拖死串行管道，必须硬超时兜底 */
function withTimeout(promise, ms, label) {
  return new Promise((resolve, reject) => {
    const t = setTimeout(() => reject(new Error(`${label} (超时 ${Math.round(ms / 1000)}s)`)), ms);
    promise.then(
      (v) => { clearTimeout(t); resolve(v); },
      (e) => { clearTimeout(t); reject(e); }
    );
  });
}

/** 同步 sleep（Atomics.wait，主线程可用，无子进程开销） */
function sleepSync(ms) {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
}

/** hermes kanban CLI 封装：--json 输出解析为 JS 值；非 JSON（claim/reclaim/comment/complete/block 等文本输出）原样返回 */
function kanban(config, args) {
  const out = execFileSync(config.hermesBin, ["kanban", "--board", config.board, ...args], {
    encoding: "utf8", stdio: ["ignore", "pipe", "pipe"]
  });
  try { return JSON.parse(out); }   // list/show --json
  catch { return out.trim(); }      // "Claimed ...", "Reclaimed ...", "Comment added ..." 等
}

/** 写操作重试（SQLite busy_timeout=5000ms 兜底后仍可能撞锁；busy/locked 重试） */
function kanbanRetry(config, args, attempts = 3) {
  for (let i = 1; ; i++) {
    try { return kanban(config, args); }
    catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      if (i >= attempts || !/busy|locked|database is locked/i.test(msg)) throw err;
      log("retry", args[0], "busy:", msg.slice(0, 80));
      sleepSync(2000);
    }
  }
}

/** 写 done 文件（Hermes 外部事件注入联动）：complete 成功后写 ~/.dsh/kanban-done/<id>.done，
 * Hermes 空闲循环发现后注入其当前会话；写失败静默降级（不影响看板回写） */
function writeDoneFile(config, task, result) {
  try {
    const dir = config.doneDir.startsWith("~/") ? join(homedir(), config.doneDir.slice(2)) : config.doneDir;
    mkdirSync(dir, { recursive: true });
    // 文件名用安全化 id（防路径分隔符/特殊字符），payload.id 保留原始 task.id 供 Hermes 展示
    const fileId = String(task.id).replace(/[^a-zA-Z0-9_-]/g, "");
    const payload = {
      id: task.id,
      title: task.title,
      result: (result || "").slice(0, 500),
      ts: Date.now(),
      status: "done"
    };
    writeFileSync(join(dir, `${fileId}.done`), JSON.stringify(payload));
    log("done file:", join(dir, `${fileId}.done`));
  } catch (err) {
    // 写失败不影响任务回写（comment/complete 已成功）
    log("done file write failed (ignored):", task.id, err instanceof Error ? err.message : String(err));
  }
}

/** 汇总一次执行的最后 assistant 文本与结束原因（与 headless 模式的 summarize 逻辑一致）。
 *  Adapted from DeepSeek Harness headless summarize (MIT). See NOTICE-借鉴与合规.md. */
function summarize(events, firstSeq) {
  let started = false, text = "", reason;
  for (const event of events) {
    if (event.seq < firstSeq) continue;
    if (event.type === "turn/start") { started = true; continue; }
    if (!started) continue;
    if (event.type === "assistant/message") {
      const joined = event.data.message.content
        .filter((b) => b.type === "text").map((b) => b.text).join("");
      if (joined !== "") text = joined;
    }
    if (event.type === "turn/end") reason = event.data.reason;
  }
  return { text, reason };
}

/** 模型翻译：读 task.model_override / provider_override（CLI 实测字段名） */
function resolveModel(config, task) {
  const spec = task.provider_override && task.model_override
    ? `${task.provider_override}/${task.model_override}`
    : (task.model_override || "");
  const hit = config.modelMap[spec] || config.modelMap[task.model_override] || config.modelMap["__fallback__"];
  return { ...hit, requested: spec || "(默认)" };
}

/** 把会话 attach 到 cwd 对应的工作区（实测：缺这一步 GUI 侧边栏看不到该会话） */
async function attachToWorkspace(registry, cwd, sessionId) {
  let ws = await registry.resolveByPath(cwd);
  if (!ws) ws = await registry.createCanonical(cwd, basename(cwd));
  await ws.attachSession(sessionId);
}

/** 在一个全新会话里跑一个任务（GUI 里"新对话"的来源） */
async function runTask(ctx, task, config) {
  const agents = ctx.get("agents");
  const defaultModel = ctx.get("agentDefaultModel");
  const sessions = ctx.get("sessions");
  const registry = ctx.get("workspaceRegistry");
  const agentPresets = ctx.get("agentPresets");
  if (!agents || !defaultModel || !sessions || !registry || !agentPresets) {
    throw new Error("missing services: " + JSON.stringify({
      agents: !!agents, defaultModel: !!defaultModel, sessions: !!sessions,
      registry: !!registry, agentPresets: !!agentPresets
    }));
  }

  await ctx.get("loader")?.await();
  const resolved = resolveModel(config, task);
  // workspace 字段实测为 workspace_kind + workspace_path（create --json），无 task.workspace
  const workdir = task.workspace_kind === "dir" && task.workspace_path
    ? task.workspace_path
    : (typeof task.workspace === "string" && task.workspace.startsWith("dir:") ? task.workspace.slice(4) : config.cwd);
  const sessionId = SessionId(`session-hermes-${String(task.id).replace(/[^a-zA-Z0-9_-]/g, "")}-${randomUUID().slice(0, 8)}`);
  log("runTask", task.id, "model", resolved.provider + "/" + resolved.model, "cwd", workdir);

  const { agent } = await agents.create({
    sessionId,
    meta: { cwd: workdir },
    agentOptions: { provider: resolved.provider, model: resolved.model },
    setup: async (agentCtx) => {
      installModelSelection(agentCtx, { current: { provider: resolved.provider, model: resolved.model }, assembled: void 0 });
      // 实测：未挂 preset 的 agent 工具层为空（dsh-agent-presets 会发出警告）——
      // 挂 standard preset 后 bash/fs 等工具才真实可用
      await agentPresets.mount(agentCtx, "standard");
    }
  });

  await agent.whenIdle();
  // 首轮前把会话固定到 watcher 专用权限预设（danger-full-access + never）：
  // 白名单落点免审批写、需要升级的请求快速失败而不是挂起等审批
  try {
    await ctx.get("permissionPresets").set(agent.session, config.permissionPreset);
  } catch (err) {
    log("permissionPreset set failed", task.id, err instanceof Error ? err.message : String(err));
  }
  const firstSeq = agent.session.seq;
  const body = typeof task.body === "string" && task.body.trim() ? `\n\n【补充】\n${task.body}` : "";
  agent.followup(createUserMessage({
    content: [{
      type: "text",
      text: `这是由 Hermes 布置的任务（看板 ${task.id}）。实际使用模型：${resolved.provider}/${resolved.model}。` +
            `\n\n${task.title}${body}`
    }],
    source: { kind: "user" }
  }));
  try {
    await withTimeout(agent.whenIdle(), config.taskTimeoutMs, `task ${task.id} 执行超时`);
  } catch (err) {
    // 超时/挂起（如审批无人应答）：释放 agent 会话，避免拖死串行管道
    try { await agent.dispose?.(); } catch { /* 忽略 */ }
    throw err;
  }
  await sessions.flush(agent.session);
  await attachToWorkspace(registry, workdir, sessionId);
  const outcome = summarize(agent.session.events, firstSeq);
  log("runTask done", task.id, "reason", outcome.reason?.kind);
  return outcome;
}

/** 单轮队列处理：认领所有 ready 任务并串行执行 */
async function drainOnce(ctx, config, running) {
  const list = kanban(config, ["list", "--json", "--assignee", config.assignee]);
  const tasks = Array.isArray(list) ? list : [];
  for (const t of tasks) {
    if (running.has(t.id) || t.status !== "ready") continue;
    running.add(t.id);
    try {
      kanbanRetry(config, ["claim", t.id]);                     // claim 无 --assignee（create 时固定）
      const shown = kanbanRetry(config, ["show", t.id, "--json"]);
      const task = (shown && shown.task) || shown || t;         // show 容器取 .task
      const outcome = await runTask(ctx, task, config);

      const result = (outcome.text || "").trim().replace(/\s+/g, " ").slice(0, 500);
      const resolved = resolveModel(config, task);
      kanbanRetry(config, ["comment", t.id,
        `[DSH] 完成于 ${new Date().toLocaleString()}；实际模型 ${resolved.provider}/${resolved.model}。\n${result}`]);
      kanbanRetry(config, ["complete", t.id, "--result", result]);
      writeDoneFile(config, task, result);   // Hermes 外部事件注入联动：done 文件的 result 与 complete --result 同源
      log("done", t.id, resolved.provider + "/" + resolved.model, outcome.reason?.kind);
    } catch (err) {
      // 错误上报：comment + block --kind（Hermes 侧 /inbox 可见）
      const msg = err instanceof Error ? err.message : String(err);
      log("error", t.id, msg);
      // 认领/读取失败且非本 watcher 的活（已被他人 claim、任务消失、非 ready 等）→ 跳过，绝不 block 别人的任务
      // 实测错误形态：cannot claim <id>: status=done/running lock=... ；no such task: <id>
      if (/cannot claim|no such task|not ready|already claimed|claimed by|not found|unknown task|no longer/i.test(msg)) {
        log("skip (not claimable)", t.id, msg.slice(0, 120));
      } else {
        try {
          kanbanRetry(config, ["comment", t.id, `[DSH] 失败于 ${new Date().toLocaleString()}：${msg.slice(0, 500)}`]);
          // 错误上报场景（超时/模型报错/沙箱拦截）本质是能力/环境问题 → --kind capability
          kanbanRetry(config, ["block", t.id, "watcher 执行失败", "--kind", "capability"]);
        } catch (e2) {
          log("error(comment failed)", t.id, e2 instanceof Error ? e2.message : String(e2));
        }
      }
    } finally {
      running.delete(t.id);
    }
  }
}

/** 崩溃恢复：启动时把 running 且非本次活动任务 reclaim 回 ready */
function recoverStaleTasks(config) {
  try {
    const list = kanban(config, ["list", "--json", "--assignee", config.assignee, "--status", "running"]);
    const stale = Array.isArray(list) ? list : [];
    for (const t of stale) {
      log("recover", t.id, "退回 ready（上次执行中断）");
      kanbanRetry(config, ["reclaim", t.id, "--reason", "watcher 重启，上次执行中断"]);
    }
  } catch (err) {
    log("recover error", err instanceof Error ? err.message : String(err));
  }
}

function apply(ctx, config) {
  // 日志接入 cordis logger：模块级 log 注入，kanbanRetry 等同步函数同样生效
  log = (...a) => ctx.logger?.("kanban-watcher")?.info?.(...a) ?? console.log("[kanban-watcher]", ...a);
  const running = new Set();
  let disposed = false;
  let busy = false;

  async function tick() {
    if (busy || disposed) return;
    busy = true;
    try { await drainOnce(ctx, config, running); }
    catch (err) { log("tick error", err instanceof Error ? err.message : String(err)); }
    finally { busy = false; }
  }

  // 0) singleton lock：PID + 存活检查（崩溃后残留可回收；EPERM/解析失败保守视为存活）
  const lockPath = join(dirname(config.triggerDir), "kanban-watcher.lock");
  mkdirSync(dirname(lockPath), { recursive: true });
  let lockFd = null;
  try {
    lockFd = openSync(lockPath, "wx");
    writeSync(lockFd, String(process.pid));
  } catch (err) {
    if (err.code !== "EEXIST") throw err;
    let holderAlive = true;
    try {
      const pid = Number(readFileSync(lockPath, "utf8").trim());
      if (Number.isInteger(pid) && pid > 0) process.kill(pid, 0);
      else holderAlive = false;
    } catch (e) {
      if (e.code === "ESRCH") holderAlive = false;
    }
    if (!holderAlive) {
      log("recovering stale lock:", lockPath);
      rmSync(lockPath, { force: true });
      lockFd = openSync(lockPath, "wx");
      writeSync(lockFd, String(process.pid));
    } else {
      log("fatal: another watcher instance is alive (lock:", lockPath, "); exiting");
      process.exit(1);
    }
  }

  // 1) 崩溃恢复（启动扫描一次）
  try { recoverStaleTasks(config); } catch (e) { log("recover fatal", String(e)); }

  // 2) 触发文件事件驱动唤醒 + 启动清理残留触发
  mkdirSync(config.triggerDir, { recursive: true });
  const watcher = fsWatch(config.triggerDir, { persistent: true }, () => { void tick(); });
  for (const f of readdirSync(config.triggerDir)) {
    if (f.endsWith(".trigger")) rmSync(join(config.triggerDir, f), { force: true });
  }

  // 3) 低频兜底轮询（fs.watch 事件可能合并/丢失）
  const timer = setInterval(() => void tick(), config.pollIntervalMs);
  timer.unref?.();

  log("started", config.board, "triggerDir:", config.triggerDir);

  // 4) 清理
  const cleanup = () => {
    if (disposed) return;
    disposed = true;
    clearInterval(timer);
    watcher.close?.();
    try { closeSync(lockFd); rmSync(lockPath, { force: true }); } catch { /* 忽略 */ }
  };
  ctx.on?.("dispose", cleanup);
  return cleanup;
}

export { Config, apply, inject, name };
